name: cla-check
version: 0.2
confinement: strict
grade: stable
summary: Check if Canonical's Contributor License Agreement has been signed
description: |
  Most projects at Canonical require contributors to sign the CLA. That
  typically means that one must check to see if a contributor has signed the
  CLA, which is where this snap comes in handy.

  You only need the email address of the contributor; run the snap with the
  following:

      $ cla-check <email address>

  The exit code will be 0 if the CLA has been signed, and non-zero otherwise.

apps:
  cla-check:
    command: cla-check
    plugs: [network, network-bind]

parts:
  python:
    plugin: python
    python-version: python2
    python-packages: [launchpadlib, simplejson]
    build-packages:
      - gcc
      - libffi-dev
      - libssl-dev

  script:
    plugin: dump
    organize:
      src/*: bin/
